#redis:
#    # redis数据库索引(默认为0)，我们使用索引为3的数据库，避免和其他数据库冲突
#    database: 11
#    # redis服务器地址（默认为loaclhost）
#    host: 172.28.9.249
#    # redis端口（默认为6379）
#    post: 16379
    # redis访问密码（默认为空）
#    password: byw@#123Rqx
#    key:  gateway:device:checkstate
#门店id

redis:
  database: 0
  host: 192.168.8.143
  post: 6379
  password: 123456
  key: 

mqtt:
  host: tcp://emqdev.bgyfoodom.com:18830
  tcpic1: deviceCmd_1000
  clientid: paho181700258583300
  username: emqdevback
  password: hLJ9sTXd1RImYqKeEzQF
  