#redis:
#    # redis数据库索引(默认为0)，我们使用索引为3的数据库，避免和其他数据库冲突
#    database: 11
#    # redis服务器地址（默认为loaclhost）
#    host: 172.28.9.249
#    # redis端口（默认为6379）
#    post: 16379
    # redis访问密码（默认为空）
#    password: byw@#123Rqx
#    key:  gateway:device:checkstate
#门店id
# V2.0.1.20.1230_001
redis:
  database: 0
  host: 127.0.0.1
  #post: 6379
  post: 59905
  password: foobared
  key: 

mqtt:
  host     : tcp://ems.bywrc.com:18830
  tcpic1   : deviceCmd_59905
  clientid : paho181700258583300
  username : prodemos
  password : Asdfghjkl;#(2020)mqttprod
  
  #host: tcp://emqdev.bgyfoodom.com:18830
  #tcpic1: deviceCmd_842
  #clientid: paho181700258583300
  #username: emqdevback
  #password: hLJ9sTXd1RImYqKeEzQF