server:
  port: 8100 # 根据具体情况修改
  servlet:
    context-path: /bgy
gateway:
  store-id: 1131756033175760890 # 根据具体情况修改
  store-type: fastfood # 根据具体情况修改(代码里没有用到，仅供标识用)
  version: 2 # 1 简版中餐  其他为2
spring:
  datasource:
    username: root
    password: zBAD#@rlkADR76h
    url: jdbc:mysql://172.28.12.246:13306/mes_fastfood_stream?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&serverTimezone=GMT%2b8

  redis:
    host: localhost
    port: 16379
    database: 6
    password: byw@#123Rqx
    timeout: 10000
    jedis:
      pool:
        max-active: 800
        max-wait: -1
        max-idle: 8
        min-idle: 0

  kafka:
    inside:
      bootstrap-servers: 172.28.12.246:29092
      consumer:
        group-id: hotpot
        enable-auto-commit: true
    #outside:
      #bootstrap-servers: 106.53.2.103:29092
      #consumer:
        #group-id: test
        #enable-auto-commit: true
  mqtt:
    dms:
      username: emqdevback
      password: hLJ9sTXd1RImYqKeEzQF
      url: tcp://emqdev.bgyfoodom.com:18830
      producerClientId: dms-fastfood-producer-${gateway.store-id}
      producerDefaultTopic: deviceStatus
      consumerClientId: dms-fastfood-consumer-${gateway.store-id}
      consumerDefaultTopic: device
      completionTimeout: 20000
      keepAliveInterval: 30
      defaultQos: 1
      willTopic: deviceOfflineNotify
      wilData: '{"restaurantId" : "1239863613804683265","code":""}'
      onlineTopic : deviceOnlineNotify
#logging:
 # level:
  #  ROOT: info
