gateway:
  store-id: 1239863613804683265 # 根据具体情况修改
  store-type: hotpot # 根据具体情况修改(代码里没有用到，仅供标识用)
  version: 2 # 1 简版中餐  其他为2
spring:
  datasource:
    username: root
    password: K4cYWk0DpzbZCkrWi028!
    url: jdbc:mysql://10.8.131.252:13306/rrs_fastfood?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&serverTimezone=GMT%2b8

  redis:
    host: localhost
    port: 6379
    database: 6
    password:
    timeout: 10000
    jedis:
      pool:
        max-active: 800
        max-wait: -1
        max-idle: 8
        min-idle: 0

  kafka:
    inside:
      bootstrap-servers: 10.8.131.252:29092
      consumer:
        group-id: test
        enable-auto-commit: true
    #outside:
      #bootstrap-servers: 203.195.241.219:29092
      #consumer:
        #group-id: test
        #enable-auto-commit: true
  mqtt:
    dms:
      username: emqdevback
      password: hLJ9sTXd1RImYqKeEzQF
      url: tcp://emqdev.bgyfoodom.com:18830
      producerClientId: dms-hotpot-producer-${gateway.store-id}
      producerDefaultTopic: deviceStatus
      consumerClientId: dms-hotpot-consumer-${gateway.store-id}
      consumerDefaultTopic: device
      completionTimeout: 20000
      keepAliveInterval: 30
      defaultQos: 1
      willTopic: deviceOfflineNotify
      wilData: '{"restaurantId" : "1239863613804683265","code":""}'
      onlineTopic : deviceOnlineNotify
#logging:
 # level:
  #  ROOT: info
