gateway:
  store-id: 1239863613804683265 # 根据具体情况修改
  store-type: fastfood # 根据具体情况修改(代码里没有用到，仅供标识用)
  version: 2  # 1 简版中餐  其他为2
spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://127.0.0.1:3306/rrs_fastfood?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&serverTimezone=GMT%2b8

  redis:
    host: localhost
    port: 6379
    database: 6
    password:
    timeout: 10000
    jedis:
      pool:
        max-active: 800
        max-wait: -1
        max-idle: 8
        min-idle: 0

  kafka:
    inside:
      bootstrap-servers: 10.8.131.250:29092
      consumer:
        group-id: hotpot
        enable-auto-commit: true
    #outside:
      #bootstrap-servers: 203.195.241.219:29092
      #consumer:
        #group-id: test
        #enable-auto-commit: true

  mqtt:
    dms:
      username: prodemos
      password: Asdfghjkl;#(2020)mqttprod
      url: tcp://ems.bywrc.com:18830
      producerClientId: dms-noodle-producer-${gateway.store-id}
      producerDefaultTopic: deviceStatus
      consumerClientId: dms-noodle-consumer-${gateway.store-id}
      consumerDefaultTopic: device
      completionTimeout: 20000
      keepAliveInterval: 30
      defaultQos: 1
      willTopic: deviceOfflineNotify
      wilData: '{"restaurantId" : "1239863613804683265","code":""}'
      onlineTopic : deviceOnlineNotify

logging:
  level:
    ROOT: info
